// lib/mockData.ts — Seed data for FreshBox AI MVP

import { FreshBox, Rental, ProductBatch, Recommendation } from "./types";

export const INITIAL_BOXES: FreshBox[] = [
  {
    id: "FB-001",
    type: "M",
    location: "Warehouse",
    status: "Rented",
    batteryLevel: 82,
    temperature: 11.5,
    humidity: 87,
    minTemp: 8,
    maxTemp: 15,
    lastSanitized: "2025-06-20",
    rentalPricePerDay: 120000,
    assignedProductId: "PROD-001",
    assignedRentalId: "RENT-001",
  },
  {
    id: "FB-002",
    type: "S",
    location: "Truck",
    status: "Rented",
    batteryLevel: 67,
    temperature: 3.2,
    humidity: 92,
    minTemp: 0,
    maxTemp: 5,
    lastSanitized: "2025-06-18",
    rentalPricePerDay: 75000,
    assignedProductId: "PROD-002",
    assignedRentalId: "RENT-002",
  },
  {
    id: "FB-003",
    type: "L",
    location: "Warehouse",
    status: "Available",
    batteryLevel: 100,
    temperature: 4.0,
    humidity: 80,
    minTemp: -5,
    maxTemp: 15,
    lastSanitized: "2025-06-24",
    rentalPricePerDay: 200000,
  },
  {
    id: "FB-004",
    type: "S",
    location: "Warehouse",
    status: "Available",
    batteryLevel: 95,
    temperature: 5.5,
    humidity: 75,
    minTemp: 0,
    maxTemp: 10,
    lastSanitized: "2025-06-23",
    rentalPricePerDay: 75000,
  },
  {
    id: "FB-005",
    type: "M",
    location: "Truck",
    status: "Available",
    batteryLevel: 88,
    temperature: 6.0,
    humidity: 78,
    minTemp: 0,
    maxTemp: 15,
    lastSanitized: "2025-06-22",
    rentalPricePerDay: 120000,
  },
  {
    id: "FB-006",
    type: "L",
    location: "Warehouse",
    status: "Maintenance",
    batteryLevel: 12,
    temperature: 20.1,
    humidity: 60,
    minTemp: -5,
    maxTemp: 15,
    lastSanitized: "2025-06-10",
    rentalPricePerDay: 200000,
  },
  {
    id: "FB-007",
    type: "M",
    location: "Warehouse",
    status: "Available",
    batteryLevel: 91,
    temperature: 7.0,
    humidity: 82,
    minTemp: 0,
    maxTemp: 15,
    lastSanitized: "2025-06-24",
    rentalPricePerDay: 120000,
  },
  {
    id: "FB-008",
    type: "S",
    location: "Truck",
    status: "Available",
    batteryLevel: 74,
    temperature: 8.0,
    humidity: 76,
    minTemp: 0,
    maxTemp: 12,
    lastSanitized: "2025-06-21",
    rentalPricePerDay: 75000,
  },
];

export const INITIAL_RENTALS: Rental[] = [
  {
    id: "RENT-001",
    userName: "PT Agro Nusantara",
    boxId: "FB-001",
    startDate: "2025-06-22",
    endDate: "2025-06-29",
    usageMode: "Storage",
    pickupLocation: "Pasar Induk Kramat Jati, Jakarta",
    destinationLocation: "Cold Storage Hub Bekasi",
    status: "Active",
    createdAt: "2025-06-22T08:00:00Z",
  },
  {
    id: "RENT-002",
    userName: "CV Laut Segar",
    boxId: "FB-002",
    startDate: "2025-06-23",
    endDate: "2025-06-26",
    usageMode: "Distribution",
    pickupLocation: "TPI Muara Baru, Jakarta",
    destinationLocation: "Superindo BSD City",
    status: "Active",
    createdAt: "2025-06-23T06:30:00Z",
  },
];

export const INITIAL_PRODUCTS: ProductBatch[] = [
  {
    id: "PROD-001",
    productName: "Tomat Horti Premium",
    category: "Tomatoes",
    batchId: "BATCH-TOM-240622",
    quantityKg: 250,
    origin: "Garut, Jawa Barat",
    destination: "Pasar Modern BSD",
    dateStored: "2025-06-22",
    expectedDeliveryDate: "2025-06-27",
    estimatedShelfLifeDays: 7,
    assignedBoxId: "FB-001",
    qualityGrade: "A",
    createdAt: "2025-06-22T08:15:00Z",
    recommendationId: "REC-001",
  },
  {
    id: "PROD-002",
    productName: "Ikan Kakap Segar",
    category: "Seafood",
    batchId: "BATCH-SEA-240623",
    quantityKg: 80,
    origin: "TPI Muara Baru",
    destination: "Superindo BSD City",
    dateStored: "2025-06-23",
    expectedDeliveryDate: "2025-06-26",
    estimatedShelfLifeDays: 3,
    assignedBoxId: "FB-002",
    qualityGrade: "A",
    createdAt: "2025-06-23T06:45:00Z",
    recommendationId: "REC-002",
  },
];

export const INITIAL_RECOMMENDATIONS: Recommendation[] = [
  {
    id: "REC-001",
    productBatchId: "PROD-001",
    recommendedTemperature: "10–13°C",
    recommendedHumidity: "85–90% RH",
    airflowLevel: "Medium",
    storageDurationLimit: "5–7 days",
    spoilageRisk: "Low",
    handlingRecommendation:
      "Store away from ethylene-producing fruits. Avoid direct cold air contact. Check daily for soft spots.",
    energyOptimizationTip:
      "Maintain steady temperature at 11°C rather than cycling. Pre-cool box before loading.",
    reasoningSummary:
      "Tomatoes are chilling-sensitive below 10°C. Moderate humidity prevents skin shrinkage while inhibiting mold. Medium airflow ensures even temperature distribution without over-drying.",
    generatedAt: "2025-06-22T08:16:00Z",
    source: "Fallback",
  },
  {
    id: "REC-002",
    productBatchId: "PROD-002",
    recommendedTemperature: "0–2°C",
    recommendedHumidity: "75–90% RH",
    airflowLevel: "High",
    storageDurationLimit: "2–3 days",
    spoilageRisk: "Medium",
    handlingRecommendation:
      "Maintain ice contact cooling. Dispatch within 48 hours. Avoid temperature fluctuations above 2°C.",
    energyOptimizationTip:
      "Pre-ice box 2 hours before loading. Use vacuum insulation panels if available.",
    reasoningSummary:
      "Fresh seafood is highly perishable and requires near-freezing temperatures. High airflow ensures cold permeation through fish mass. Short duration limit due to natural decomposition rate.",
    generatedAt: "2025-06-23T06:46:00Z",
    source: "Fallback",
  },
];
